### ISSUE TITLE
Problem in importing

### ISSUE THREAD

**Issue by dstvishnu** [protobi/js-xlsx#93] opened 2017-11-20 17:03 UTC
#79  i tried to import xlsx-style i am getting the following error

```
ERROR in ./~/xlsx-style/dist/cpexcel.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./cptable in C:\Users\ExportToExcel\node_modules\xlsx-style\dist
 @ ./~/xlsx-style/dist/cpexcel.js 807:16-41
```

Is there is any possible solution?

**Comment by pietersv** [comment] 2017-11-21 04:39
@dstvishnu  How are you importing the code?  Are you referencing `xlsx.full.min.js`?  I believe that should have key dependencies included

**Comment by pietersv** [comment] 2017-11-21 17:31
Duplicate of https://github.com/protobi/js-xlsx/issues/92?

**Closed by pietersv** 2017-11-21 17:31 UTC

**Comment by dstvishnu** [comment] 2017-11-21 17:38
@pietersv  i changed the webpack configiration  to exclude the cpexcel.js odc.js.After that i am not facing any issue
